"""Removed redundant columns: expiration date and token, i have decided to abstract it all away with jwt

Revision ID: 540727784959
Revises: bec83e0103c8
Create Date: 2025-05-29 20:07:20.257810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '540727784959'
down_revision: Union[str, None] = 'bec83e0103c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('verification_token'))
        batch_op.drop_column('verification_token')
        batch_op.drop_column('verification_token_expires_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token_expires_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('verification_token'), ['verification_token'], unique=True)

    # ### end Alembic commands ###
